language: python
sudo: false
addons:
  apt:
    packages:
      - luarocks
cache:
  timeout: 1000
  directories:
    - $HOME/.luarocks
before_install:
  - luarocks install --local luacheck
  - pip3 install pre-commit
script:
  - pre-commit run --all-files
  - $HOME/.luarocks/bin/luacheck .
notifications:
  email: false
